# This file was generated by GoReleaser. DO NOT EDIT.
cask "phs-mcp" do
  name "phs-mcp"
  desc "MCP server for the Platform Hosting Services API"
  homepage "https://github.com/NethermindEth/angkor-platform-api"
  version "0.4.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "phs-mcp"

  on_macos do
    on_intel do
      url "https://github.com/NethermindEth/homebrew-phs/releases/download/v#{version}/phs-mcp_#{version}_darwin_amd64.tar.gz"
      sha256 "b70330dbf1528160d95dc198e588ca259e7a2bde77e65c4c25ba1fdde915e10c"
    end
    on_arm do
      url "https://github.com/NethermindEth/homebrew-phs/releases/download/v#{version}/phs-mcp_#{version}_darwin_arm64.tar.gz"
      sha256 "4a291e4b60d1ef830031b8dc3d1c71fe1c3dff45b50fee5800a98a969c7a8217"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/NethermindEth/homebrew-phs/releases/download/v#{version}/phs-mcp_#{version}_linux_amd64.tar.gz"
      sha256 "f7ba5a46da60b6699b383386277e74f553398104c2e783063daf0b4f18a7cf52"
    end
    on_arm do
      url "https://github.com/NethermindEth/homebrew-phs/releases/download/v#{version}/phs-mcp_#{version}_linux_arm64.tar.gz"
      sha256 "11c0f76976c4c7efce50ed34dde051eee695ccea115b458ba019c49346d551e3"
    end
  end

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/phs-mcp"]
  end

  caveats do
    "Binary is not Apple-signed. macOS may show a Gatekeeper warning on first run."
  end

  # No zap stanza required
end
