# This file was generated by GoReleaser. DO NOT EDIT.
cask "phs-mcp" do
  name "phs-mcp"
  desc "MCP server for the Platform Hosting Services API"
  homepage "https://github.com/NethermindEth/angkor-platform-api"
  version "0.3.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "phs-mcp"

  on_macos do
    on_intel do
      url "https://github.com/NethermindEth/homebrew-phs/releases/download/v#{version}/phs-mcp_#{version}_darwin_amd64.tar.gz"
      sha256 "6a13b315dfea91758a8c50592c9ec1dac76a8a79d8509d5b679c2f2470604b87"
    end
    on_arm do
      url "https://github.com/NethermindEth/homebrew-phs/releases/download/v#{version}/phs-mcp_#{version}_darwin_arm64.tar.gz"
      sha256 "0a94d66fc141a65a20d0d1f76280f525cdeb37c42c1743d9405c347efd157810"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/NethermindEth/homebrew-phs/releases/download/v#{version}/phs-mcp_#{version}_linux_amd64.tar.gz"
      sha256 "44accdc20b452301eb5e42f8be0785348947eb2d46ddbe884d3c2b3f20e0a731"
    end
    on_arm do
      url "https://github.com/NethermindEth/homebrew-phs/releases/download/v#{version}/phs-mcp_#{version}_linux_arm64.tar.gz"
      sha256 "6118deecb77bc358f33f619395c29f34c26cd4cf825dd7553cfcb36008177e63"
    end
  end

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/phs-mcp"]
  end

  caveats do
    "Binary is not Apple-signed. macOS may show a Gatekeeper warning on first run."
  end

  # No zap stanza required
end
