# This file was generated by GoReleaser. DO NOT EDIT.
cask "phs-mcp" do
  name "phs-mcp"
  desc "MCP server for the Platform Hosting Services API"
  homepage "https://github.com/NethermindEth/angkor-platform-api"
  version "0.5.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "phs-mcp"

  on_macos do
    on_intel do
      url "https://github.com/NethermindEth/homebrew-phs/releases/download/v#{version}/phs-mcp_#{version}_darwin_amd64.tar.gz"
      sha256 "8bf61fb9e1bf61e1ccb9131cdab433e10ea739c2945edf60074aed56eb020536"
    end
    on_arm do
      url "https://github.com/NethermindEth/homebrew-phs/releases/download/v#{version}/phs-mcp_#{version}_darwin_arm64.tar.gz"
      sha256 "a9a6b673a01df4b861d1d2752ff6ec335cef330fe3d90ee354d7b974a1401712"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/NethermindEth/homebrew-phs/releases/download/v#{version}/phs-mcp_#{version}_linux_amd64.tar.gz"
      sha256 "037d2bde413e0329dd030b3c6824e8608bf6aa326718f7fbc7cfc39e699ad9ea"
    end
    on_arm do
      url "https://github.com/NethermindEth/homebrew-phs/releases/download/v#{version}/phs-mcp_#{version}_linux_arm64.tar.gz"
      sha256 "2b4c79d7b852c748a46469ffdcc3a6eae4870267828d24b682ba294941eac71e"
    end
  end

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/phs-mcp"]
  end

  caveats do
    "Binary is not Apple-signed. macOS may show a Gatekeeper warning on first run."
  end

  # No zap stanza required
end
