# This file was generated by GoReleaser. DO NOT EDIT.
cask "phs" do
  name "phs"
  desc "CLI for the Platform Hosting Services API"
  homepage "https://github.com/NethermindEth/angkor-platform-api"
  version "0.5.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "phs"

  on_macos do
    on_intel do
      url "https://github.com/NethermindEth/homebrew-phs/releases/download/v#{version}/phs_#{version}_darwin_amd64.tar.gz"
      sha256 "7d322fc4ef23472fe8ea4364cb685909eb1a6430670226d10cb9771a892fa12d"
    end
    on_arm do
      url "https://github.com/NethermindEth/homebrew-phs/releases/download/v#{version}/phs_#{version}_darwin_arm64.tar.gz"
      sha256 "750e77b12bffbe45007a1dd5ef65469683880518cb1ec9999b41733f4bf2f27f"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/NethermindEth/homebrew-phs/releases/download/v#{version}/phs_#{version}_linux_amd64.tar.gz"
      sha256 "d3f539dc869ae9c2fac972b82f906c5032e8b2347ab609b382d833eca45fd5ee"
    end
    on_arm do
      url "https://github.com/NethermindEth/homebrew-phs/releases/download/v#{version}/phs_#{version}_linux_arm64.tar.gz"
      sha256 "8b6ec81a3e5948c08b0bd457787ffa202c1d60ab5531a809fc07e31ade59c3f3"
    end
  end

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/phs"]
  end

  caveats do
    "Binary is not Apple-signed. macOS may show a Gatekeeper warning on first run."
  end

  # No zap stanza required
end
