# This file was generated by GoReleaser. DO NOT EDIT.
cask "phs" do
  name "phs"
  desc "CLI for the Platform Hosting Services API"
  homepage "https://github.com/NethermindEth/angkor-platform-api"
  version "0.2.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "phs"

  on_macos do
    on_intel do
      url "https://github.com/NethermindEth/homebrew-phs/releases/download/v#{version}/phs_#{version}_darwin_amd64.tar.gz"
      sha256 "7184225a8ab20c0cf650c68ee6aeda35c7001874b58da225b9bfe3c593c925b6"
    end
    on_arm do
      url "https://github.com/NethermindEth/homebrew-phs/releases/download/v#{version}/phs_#{version}_darwin_arm64.tar.gz"
      sha256 "f45f616cf952bc461dac706dbebd10da1bf2456dd705412d0bd27a7821f18b10"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/NethermindEth/homebrew-phs/releases/download/v#{version}/phs_#{version}_linux_amd64.tar.gz"
      sha256 "91fbb4fcd9c4a335d6a0aaeeada6f6efb9235875068251bb79ce77b90d02823b"
    end
    on_arm do
      url "https://github.com/NethermindEth/homebrew-phs/releases/download/v#{version}/phs_#{version}_linux_arm64.tar.gz"
      sha256 "6bb6e4a2b8f96da2eb99940177b29bedb2a1b3c9569614d799b944d45154edf9"
    end
  end

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/phs"]
  end

  caveats do
    "Binary is not Apple-signed. macOS may show a Gatekeeper warning on first run."
  end

  # No zap stanza required
end
