# This file was generated by GoReleaser. DO NOT EDIT.
cask "phs" do
  name "phs"
  desc "CLI for the Platform Hosting Services API"
  homepage "https://github.com/NethermindEth/angkor-platform-api"
  version "0.2.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "phs"

  on_macos do
    on_intel do
      url "https://github.com/NethermindEth/homebrew-phs/releases/download/v#{version}/phs_#{version}_darwin_amd64.tar.gz"
      sha256 "8376af9421cafd81ba4de93c734ed3c3f407021ab4b476f1f033256427f531e8"
    end
    on_arm do
      url "https://github.com/NethermindEth/homebrew-phs/releases/download/v#{version}/phs_#{version}_darwin_arm64.tar.gz"
      sha256 "7ed1afaf50dd4d63ce03b6da8f5ca8db507a4fece5957581b3d1c2eac0d22bf8"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/NethermindEth/homebrew-phs/releases/download/v#{version}/phs_#{version}_linux_amd64.tar.gz"
      sha256 "31c4e8a14a1729231207518b8b8e35ac5325360d8703c371839473d0991ec5f3"
    end
    on_arm do
      url "https://github.com/NethermindEth/homebrew-phs/releases/download/v#{version}/phs_#{version}_linux_arm64.tar.gz"
      sha256 "ec3188039890596ad763841fd75996ed9a4f46b0ba94fe641fce9c60844c1d25"
    end
  end

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/phs"]
  end

  caveats do
    "Binary is not Apple-signed. macOS may show a Gatekeeper warning on first run."
  end

  # No zap stanza required
end
