# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class PhsMcp < Formula
  desc "MCP server for the Platform Hosting Services API"
  homepage "https://github.com/NethermindEth/angkor-platform-api"
  version "0.10.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/NethermindEth/homebrew-phs/releases/download/v0.10.0/phs-mcp_0.10.0_darwin_amd64.tar.gz"
      sha256 "428789e7fbace2182724903bc908340ef74ab544a1c5bd1b2f80f87f7d86d77a"

      define_method(:install) do
        bin.install "phs-mcp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/NethermindEth/homebrew-phs/releases/download/v0.10.0/phs-mcp_0.10.0_darwin_arm64.tar.gz"
      sha256 "31ac44d013718579266beb5c1fcfffc534033bb3964c49d423e2ca2ef7858fd6"

      define_method(:install) do
        bin.install "phs-mcp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/NethermindEth/homebrew-phs/releases/download/v0.10.0/phs-mcp_0.10.0_linux_amd64.tar.gz"
      sha256 "4c98f97d129db23100757df82419f9b9aa417a2f9afec98383a98bfc6e603a84"
      define_method(:install) do
        bin.install "phs-mcp"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/NethermindEth/homebrew-phs/releases/download/v0.10.0/phs-mcp_0.10.0_linux_arm64.tar.gz"
      sha256 "70776e09b559092cda87b399047d8d36d38b06cec3ce177ebf35bbb11fe19cb1"
      define_method(:install) do
        bin.install "phs-mcp"
      end
    end
  end

  test do
    system "#{bin}/phs-mcp", "--version"
  end
end
