# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Phs < Formula
  desc "CLI for the Platform Hosting Services API"
  homepage "https://github.com/NethermindEth/angkor-platform-api"
  version "0.8.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/NethermindEth/homebrew-phs/releases/download/v0.8.1/phs_0.8.1_darwin_amd64.tar.gz"
      sha256 "1cb5b62f8ed25d6be334010dd4aca33140a186da3bbb7efb162655fc9fb1395f"

      define_method(:install) do
        bin.install "phs"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/NethermindEth/homebrew-phs/releases/download/v0.8.1/phs_0.8.1_darwin_arm64.tar.gz"
      sha256 "0d3c46c498d1501bab82d086ecece3c507bb19af12bcceb9c60f7ca6c6f6a6ec"

      define_method(:install) do
        bin.install "phs"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/NethermindEth/homebrew-phs/releases/download/v0.8.1/phs_0.8.1_linux_amd64.tar.gz"
      sha256 "4250712e4187c015eef8b2ea9c8f5b476da4c46ea693668cce2cda5ebcb7c7fc"
      define_method(:install) do
        bin.install "phs"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/NethermindEth/homebrew-phs/releases/download/v0.8.1/phs_0.8.1_linux_arm64.tar.gz"
      sha256 "bcc8dc39c241c3aef144e1dc81bb5c6382030c8067e1c87073233a0f036a6e14"
      define_method(:install) do
        bin.install "phs"
      end
    end
  end

  test do
    system "#{bin}/phs", "--version"
  end
end
