# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Phs < Formula
  desc "CLI for the Platform Hosting Services API"
  homepage "https://github.com/NethermindEth/angkor-platform-api"
  version "0.8.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/NethermindEth/homebrew-phs/releases/download/v0.8.0/phs_0.8.0_darwin_amd64.tar.gz"
      sha256 "7e70e9ba32a05860340ba0d5e317d93c310057b010636cd033bf450c6832f621"

      define_method(:install) do
        bin.install "phs"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/NethermindEth/homebrew-phs/releases/download/v0.8.0/phs_0.8.0_darwin_arm64.tar.gz"
      sha256 "08d74d07e992608af8132daa87a92f6d919e91ec6b2fcdb1d19db2164782425f"

      define_method(:install) do
        bin.install "phs"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/NethermindEth/homebrew-phs/releases/download/v0.8.0/phs_0.8.0_linux_amd64.tar.gz"
      sha256 "25f4e3b95ab5e917bffe2d4d23fea76efd40f16d4018ffacb67c2c370a2ee6d3"
      define_method(:install) do
        bin.install "phs"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/NethermindEth/homebrew-phs/releases/download/v0.8.0/phs_0.8.0_linux_arm64.tar.gz"
      sha256 "ef1bf2ac6510ca395fca57600186f2146de1610ef6ba1e2964d5b989ded967fa"
      define_method(:install) do
        bin.install "phs"
      end
    end
  end

  test do
    system "#{bin}/phs", "--version"
  end
end
